FROM node:20.5.0-alpine3.18
RUN addgroup clientuser && adduser -S -G clientuser clientuser
USER clientuser
WORKDIR /app/
COPY --chown=clientuser:clientuser package*.json .
RUN npm install
COPY  --chown=clientuser:clientuser . .
EXPOSE 4200
CMD ["npm","start"]