services:
  angular: 
    build: 
      context: ./client
      dockerfile: dockerfile
    container_name: newtime-client
    ports:
      - 4200:4200
    volumes:
      - ./client/src:/app/src

  laravel:
    build: 
      context: ./api
      dockerfile: dockerfile
    container_name: newtime-api
    ports:
      - 8000:8000
    volumes:
      - ./api:/var/www/html
      - ./api/vendor:/var/www/html/vendor
      - ./api/storage:/var/www/html/storage
    environment:
      APP_ENV: local
      APP_DEBUG: true
      ALLOWED_ORIGIN: http://localhost:4200
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USERNAME: user_test
      DB_PASSWORD: test
    depends_on:
      - mysql
    command: >
      sh -c "
       until nc -z -v -w30 mysql 3306; do
        echo 'Waiting for MySQL...';
        sleep 5;
      done;
      echo 'MySQL is up - executing command';

      php artisan key:generate &&
      php artisan migrate --force &&
      php artisan db:seed --force --class=UsersTableSeeder &&
      php artisan serve --host=0.0.0.0 --port=8000
      "

  mysql:
    image: mysql:8.0
    container_name: newtime-mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test
      MYSQL_USER: user_test
      MYSQL_PASSWORD: test

volumes:
  test: